apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-creator
  namespace: dev
secrets:
  - name: github-ssh
  - name: image-push-creds
  - name: image-pull-creds
imagePullSecrets:
  - name: image-pull-creds