apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: base
  namespace: dev
spec:
  tag: gcr.io/ps-smalik/kpack/builder/base
  serviceAccount: image-creator
  stack:
    name: base
    kind: ClusterStack
  store:
    name: base
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/nginx
